//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTR.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTR.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;cards xmlns=&quot;http://tempuri.org/CardsSchema.xsd&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://tempuri.org/ CardsSchema.xsd&quot;&gt;
        ///  &lt;!--Brick--&gt;
        ///  &lt;card&gt;
        ///    &lt;building&gt;Academy&lt;/building&gt;
        ///    &lt;material&gt;brick&lt;/material&gt;
        ///    &lt;description&gt;You may execute one Thinker action after any turn in which you execute at least one Craftsman action.&lt;/description&gt;
        ///  &lt;/card&gt;
        ///  &lt;card&gt;
        ///    &lt;building&gt;Atrium&lt;/building&gt;
        ///    &lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy,4
        ///Atrium,4
        ///Bath,4
        ///Foundry,4
        ///Gate,4
        ///School,4
        ///Shrine,4
        ///Amphitheatre,4
        ///Aqueduct,4
        ///Bridge,4
        ///Senate,4
        ///Storeroom,4
        ///Tower,4
        ///Vomitorium,4
        ///Wall,4
        ///Basilica,4
        ///Fountain,4
        ///Forum,4
        ///Ludus Magnus,4
        ///Palace,4
        ///Stairway,4
        ///Statue,4
        ///Temple,4
        ///Bar,4
        ///Insula,4
        ///Latrine,4
        ///Road,4
        ///Catacomb,4
        ///Circus Maximus,4
        ///Coliseum,4
        ///Garden,4
        ///Prison,4
        ///Scriptorium,4
        ///Sewer,4
        ///Villa,4
        ///Circus,4
        ///Dock,4
        ///Market,4
        ///Palisade,4.
        /// </summary>
        internal static string imperialdeck {
            get {
                return ResourceManager.GetString("imperialdeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy,4
        ///Atrium,4
        ///Bath,4
        ///Foundry,4
        ///Gate,4
        ///School,4
        ///Shrine,4
        ///Amphitheatre,4
        ///Aqueduct,4
        ///Bridge,4
        ///Senate,4
        ///Storeroom,4
        ///Tower,4
        ///Vomitorium,4
        ///Wall,4
        ///Basilica,4
        ///Fountain,4
        ///Forum,4
        ///Ludus Magnus,4
        ///Palace,4
        ///Stairway,4
        ///Statue,4
        ///Temple,4
        ///Bar,4
        ///Insula,4
        ///Latrine,4
        ///Road,4
        ///Catacomb,4
        ///Circus Maximus,4
        ///Coliseum,4
        ///Garden,4
        ///Prison,4
        ///Scriptorium,4
        ///Sewer,4
        ///Villa,4
        ///Circus,4
        ///Dock,4
        ///Market,4
        ///Palisade,4.
        /// </summary>
        internal static string republicdeck {
            get {
                return ResourceManager.GetString("republicdeck", resourceCulture);
            }
        }
    }
}
