//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTR.Tiber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTR.Tiber.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already joined the game!.
        /// </summary>
        internal static string AlreadyJoined {
            get {
                return ResourceManager.GetString("AlreadyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is at max capacity..
        /// </summary>
        internal static string GameFull {
            get {
                return ResourceManager.GetString("GameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That move was not valid..
        /// </summary>
        internal static string IllegalMove {
            get {
                return ResourceManager.GetString("IllegalMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization was not valid..
        /// </summary>
        internal static string InvalidAuth {
            get {
                return ResourceManager.GetString("InvalidAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching game was found..
        /// </summary>
        internal static string NonexistentGame {
            get {
                return ResourceManager.GetString("NonexistentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you&apos;re not the host, you can&apos;t do that..
        /// </summary>
        internal static string NotGameHost {
            get {
                return ResourceManager.GetString("NotGameHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not currently the player&apos;s turn, or the player did not submit a turn in time..
        /// </summary>
        internal static string NotPlayerTurn {
            get {
                return ResourceManager.GetString("NotPlayerTurn", resourceCulture);
            }
        }
    }
}
